baseURL = 'http://motonarikambara.github.io/'
defaultContentLanguage = 'ja'
# title = "Motonari Kambara"
theme = "hugo-initio"

[languages]
    [languages.ja]
        languageName = "Japanese"
        title = "Motonari Kambara"
    [languages.en]
        languageName = "English"
        title = "Motonari Kambara"


[params]
    name = "Motonari Kambara"
    # description = "Motonari Kambara's portfolio"
    email = "motonari.k714@keio.jp"
    # phone = "+81 80-1381-5738"
    avatar = "images/hp.png"
    avatarclass = "circle"
    background = ""
    banner = "images/bg.jpeg"
    favicon = "images/gt_favicon.png"
    author = "Motnari Kambara"
    DateForm = "August, 2022"
    showSubheader = true
    # showServices = true
    showRecentWorks = true
    # showDownloads = true
    # showClients = true

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 5
[[menu.main]]
    name = "Profile"
    url = "/profile/"
    weight = 5

# [params.disqus]
#     site = "hugo-initio-site.disqus.com"

# [params.sharethis]
#     property = "123456789012345678901234"
#     custom = true

[params.google.analytics]
    trackerID = "G-3R7Q5YFDBK"

# [[params.social]]
# 	title = "facebook"
# 	url = "https://www.facebook.com/nickname"
#     icon = "fab fa-facebook-square"
#     footer = true
#     sharethis = true
#     network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/MotonariKambara"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
# [[params.social]]
# 	title = "instagram"
# 	url = "https://www.instagram.com/nickname"
#     icon = "fab fa-instagram"
#     footer = true
#     sharethis = false
#     network = ""
# [[params.social]]
# 	title = "google+"
# 	url = "https://plus.google.com/+nickname"
#     icon = "fab fa-google-plus-square"
#     footer = false
#     sharethis = true
#     network = "googleplus"
# [[params.social]]
# 	title = "linkedin"
# 	url = "https://www.linkedin.com/in/nickname"
#     icon = "fab fa-linkedin"
#     footer = false
#     sharethis = true
#     network = "linkedin"
# [[params.social]]
# 	title = "tumblr"
# 	url = "https://nickname.tumblr.com"
#     icon = "fab fa-tumblr-square"
#     footer = false
#     sharethis = false
#     network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/motonarikambara"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "speaker-deck"
	url = "https://speakerdeck.com/motonarikambara"
    icon = "fab fa-speaker-deck"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "motonari.k714@keio.jp"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"